# Generated by Django 3.0.8 on 2020-07-17 17:41

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptor_details',
            name='donor_details',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
