# Generated by Django 3.0.8 on 2020-07-17 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0002_auto_20200717_2311'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acceptor_details',
            new_name='Request_details',
        ),
    ]
